Update install.md with GPG key addition via trusted.gpg.d and add instructions to install Gazebo CMake from source
gazebosim/gz-tools pull request #144
Opened 2024-09-05 13:56 UTC by trushant05

# 🦟 Bug fix

Fixes #<NUMBER>

## Summary
Update install.md with GPG key addition via trusted.gpg.d and add instructions to install Gazebo CMake from source

## Checklist
- [x] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-09-05 15:34 UTC, azeey commented
@j-rivero mind taking a look. Does this line up with the latest recommended installation instructions elsewhere?

2024-09-06 09:00 UTC, ahcorde commented on tutorials/install.md
> +```
```suggestion
```bash
```

2024-09-09 22:02 UTC, azeey requested changes

2024-09-09 22:02 UTC, azeey commented on tutorials/install.md
> +In case the Gazebo CMake binary didn't work out for you, you can make it from source using following command:
Adding the repository is covered above int his file. Is it necessary to repeat it here?

2024-09-11 21:00 UTC, azeey commented on tutorials/install.md
> +wget -qO - http://packages.osrfoundation.org/gazebo.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/gazebo-archive-keyring.gpg > /dev/null
Other instructions, ([example](https://gazebosim.org/docs/latest/install_ubuntu/)) use the following. I'd suggest we do that here as well for consistency.

```
sudo curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
```

2025-03-21 15:50 UTC, caguero commented
@trushant05, could you check Addisu's suggestion?

2025-05-01 13:35 UTC, caguero commented
> @trushant05, could you check Addisu's suggestion?

@trushant05 , could you update the PR with Addisu's comments?

2025-05-08 06:08 UTC, trushant05 commented
@caguero apologies for the delay, I have updated the PR. Let me know if it requires additional modification.

2025-06-18 16:41 UTC, caguero approved these changes

2025-06-18 16:42 UTC, merged